const rooms=["Cucina","Bagno","Camera","Soggiorno","Lavanderia","Terrazzo"];
const roomEmoji={Cucina:"🍳",Bagno:"🚿",Camera:"🛏️",Soggiorno:"🛋️",Lavanderia:"🧺",Terrazzo:"🌿"};
const defaultTasks=[
{id:1,name:"Pulire piano cottura",room:"Cucina",type:"recurring",frequency:2,duration:10,lastDone:null,history:[]},
{id:2,name:"Pulire pavimento cucina",room:"Cucina",type:"recurring",frequency:7,duration:15,lastDone:null,history:[]},
{id:3,name:"Pulire frigorifero",room:"Cucina",type:"recurring",frequency:30,duration:20,lastDone:null,history:[]},
{id:4,name:"Pulire filtro lavastoviglie",room:"Cucina",type:"periodic",frequency:null,duration:10,lastDone:"2026-10-05",history:["2026-10-05","2026-08-18","2026-07-02"]},
{id:5,name:"Pulire sanitari",room:"Bagno",type:"recurring",frequency:3,duration:15,lastDone:null,history:[]},
{id:6,name:"Pulire doccia",room:"Bagno",type:"recurring",frequency:7,duration:20,lastDone:null,history:[]},
{id:7,name:"Cambiare lenzuola",room:"Camera",type:"recurring",frequency:7,duration:10,lastDone:null,history:[]},
{id:8,name:"Aspirapolvere",room:"Soggiorno",type:"recurring",frequency:3,duration:20,lastDone:null,history:[]}
];
const ideas={
Cucina:["Pulire sopra i pensili","Lavare filtro della cappa","Pulire guarnizioni frigorifero","Sgrassare ante e maniglie","Pulire internamente i cassetti","Pulire piccoli elettrodomestici"],
Bagno:["Disincrostare soffione","Pulire fughe","Lavare tappetini","Pulire scarichi","Pulire ventola/aspiratore"],
Camera:["Aspirare sotto il letto","Lavare cuscini","Pulire interno armadio","Spolverare sopra l’armadio","Lavare tende"],
Soggiorno:["Aspirare divano","Pulire battiscopa","Lavare tende","Pulire dietro i mobili","Spolverare lampade"],
Lavanderia:["Pulire filtro lavatrice","Pulire cassetto detersivo","Pulire guarnizione lavatrice","Decalcificare lavatrice"],
Terrazzo:["Pulire ringhiere","Lavare pavimento esterno","Pulire vasi","Potare foglie secche"]};
let state=JSON.parse(localStorage.getItem("casaState"))||{tasks:defaultTasks,completedToday:0,currentView:"today"};
let selectedType="recurring",currentRoom="Cucina",currentRoomTab="tasks";
function save(){localStorage.setItem("casaState",JSON.stringify(state))}
function fmtDate(iso){if(!iso)return"Mai";return new Date(iso+"T12:00:00").toLocaleDateString("it-IT",{day:"numeric",month:"long",year:"numeric"})}
function todayISO(){const d=new Date();const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,"0"),day=String(d.getDate()).padStart(2,"0");return `${y}-${m}-${day}`}
function addDaysISO(iso,days){const d=new Date(iso+"T12:00:00");d.setDate(d.getDate()+days);return d.toISOString().slice(0,10)}
function isCompletedToday(t){return (t.history||[]).includes(todayISO())}
function dueDate(t){if(t.type!=="recurring"||!t.frequency)return null;return t.lastDone?addDaysISO(t.lastDone,t.frequency):todayISO()}
function tasksForRange(range){
 const today=todayISO();
 if(range==="all")return state.tasks.filter(t=>!isCompletedToday(t));
 if(range==="week"){const end=addDaysISO(today,7);return state.tasks.filter(t=>!isCompletedToday(t)&&t.type==="recurring"&&dueDate(t)<=end)}
 return state.tasks.filter(t=>!isCompletedToday(t)&&t.type==="recurring"&&dueDate(t)<=today)
}
function taskMeta(t){const type=t.type==="recurring"?`Ogni ${t.frequency} giorni`:t.type==="periodic"?"Senza scadenza":"Una tantum";return `${type} · ${t.duration} min`}
function nav(view){state.currentView=view;save();document.querySelectorAll(".nav-item").forEach(b=>b.classList.toggle("active",b.dataset.view===view));render()}
document.querySelectorAll(".nav-item").forEach(b=>b.addEventListener("click",()=>nav(b.dataset.view)));
function taskIcon(t){const n=t.name.toLowerCase();if(n.includes("piano cottura"))return"▦";if(n.includes("pavimento"))return"⌁";if(n.includes("frigorifero"))return"▥";if(n.includes("lavastoviglie"))return"◉";return roomEmoji[t.room]||"✓"}
function taskRow(t,showRoom=true){return `<div class="task-row"><button class="check" onclick="completeTask(${t.id})">✓</button><span class="task-icon">${taskIcon(t)}</span><div class="task-main" onclick="openTask(${t.id})"><div class="task-name">${t.name}</div><div class="task-meta">${showRoom?t.room+" · ":""}${taskMeta(t)}</div></div><span class="chev">›</span></div>`}
function renderToday(){const range=state.homeRange||"today";const t=tasksForRange(range);const labels={today:"Oggi",week:"Questa settimana",all:"Tutte"};return `<div class="home-tabs"><button class="${range==="today"?"active":""}" onclick="setHomeRange('today')">Oggi</button><button class="${range==="week"?"active":""}" onclick="setHomeRange('week')">Questa settimana</button><button class="${range==="all"?"active":""}" onclick="setHomeRange('all')">Tutte</button></div><div class="today-hero"><div><b>${t.length}</b><span>${range==="today"?"attività da fare oggi":range==="week"?"attività nei prossimi 7 giorni":"attività da fare"} ›</span></div><div class="hero-plant">🌿</div></div><div class="summary"><div class="stat"><span class="stat-icon blue">▤</span><b>${t.length}</b><small>da fare</small></div><div class="stat"><span class="stat-icon coral">▣</span><b>${state.tasks.filter(x=>x.type==="periodic"&&!isCompletedToday(x)).length}</b><small>periodiche</small></div><div class="stat"><span class="stat-icon green">✓</span><b>${state.tasks.filter(isCompletedToday).length}</b><small>completate</small></div></div><section class="section"><div class="section-head"><div class="section-title">${labels[range]}</div></div><div class="card">${t.length?t.map(x=>taskRow(x)).join(""):'<div class="empty">Nessuna attività da fare qui 🎉</div>'}</div></section><section class="section"><div class="section-head"><div class="section-title">Ultime attività</div><button class="secondary" onclick="showHistory()">Vedi storico</button></div><div class="card">${recentHistory(3)}</div></section>`}
function setHomeRange(range){state.homeRange=range;save();render()}
function renderCleaning(){return `<div class="filters"><button class="active">Tutte</button><button>Oggi</button><button>Settimana</button><button>Scadute</button></div>${rooms.map(r=>{const ts=state.tasks.filter(t=>t.room===r);if(!ts.length)return"";return `<section class="section"><div class="section-head"><div class="section-title">${roomEmoji[r]} ${r}</div><span class="chip">${ts.length} attività</span></div><div class="card">${ts.map(x=>taskRow(x,false)).join("")}</div></section>`}).join("")}`}
function renderRoutines(){return `<div class="card routine"><div class="routine-head"><div><h3>🌙 Reset serale</h3><div class="task-meta">15 minuti</div></div><button class="primary">▶</button></div><ul><li>Sistemare cucina</li><li>Riordinare superfici</li><li>Lavastoviglie</li></ul></div><div style="height:12px"></div><div class="card routine"><div class="routine-head"><div><h3>☀️ Pulizie del sabato</h3><div class="task-meta">60 minuti</div></div><button class="primary">▶</button></div><ul><li>Bagno</li><li>Aspirapolvere</li><li>Pavimenti</li><li>Cambio lenzuola</li></ul></div><section class="section"><button class="primary full" onclick="alert('Nella prossima versione: routine automatica usando solo le tue attività già salvate.')">✨ Crea routine da 15 / 30 / 60 min</button></section>`}
function renderHome(){return `<div class="today-intro"><div><div class="today-date">I tuoi spazi</div><div class="today-note">Tutto organizzato stanza per stanza.</div></div></div><div class="room-grid">${rooms.map(r=>{const count=state.tasks.filter(t=>t.room===r).length;const last=state.tasks.filter(t=>t.room===r&&t.lastDone).sort((a,b)=>b.lastDone.localeCompare(a.lastDone))[0];return `<button class="room-card" data-room="${r}" onclick="openRoom(this.dataset.room)"><div class="room-art">${roomEmoji[r]}</div><div class="room-body"><b>${r}</b><small>${count} attività${last?" · ultima "+fmtDate(last.lastDone):""}</small></div></button>`}).join("")}</div>`}
function openRoom(room){currentRoom=room;currentRoomTab="tasks";state.currentView="room";render()}
function renderRoom(){const ts=state.tasks.filter(t=>t.room===currentRoom);const tabs=`<div class="tabs"><button class="${currentRoomTab==="tasks"?"active":""}" onclick="roomTab('tasks')">Attività</button><button class="${currentRoomTab==="maintenance"?"active":""}" onclick="roomTab('maintenance')">Manutenzione</button><button class="${currentRoomTab==="ideas"?"active":""}" onclick="roomTab('ideas')">Idee</button><button class="${currentRoomTab==="history"?"active":""}" onclick="roomTab('history')">Storico</button></div>`;let body="";if(currentRoomTab==="tasks"){body=`<div class="section-head"><div class="section-title">Le mie attività</div><button class="secondary" onclick="openAdd('${currentRoom}')">＋ Aggiungi</button></div><div class="card">${ts.length?ts.map(x=>taskRow(x,false)).join(""):'<div class="empty">Nessuna attività ancora.</div>'}</div>`}else if(currentRoomTab==="maintenance"){const p=ts.filter(t=>t.type!=="recurring");body=`<div class="section-title" style="margin-bottom:10px">Manutenzione e attività periodiche</div><div class="card">${p.length?p.map(x=>taskRow(x,false)).join(""):'<div class="empty">Nessuna manutenzione salvata.</div>'}</div>`}else if(currentRoomTab==="ideas"){body=`<div class="section-title" style="margin-bottom:4px">✨ Idee per ${currentRoom.toLowerCase()}</div><p class="muted" style="margin-top:0">Spunti da aggiungere solo se ti servono.</p><div class="card">${(ideas[currentRoom]||[]).map(i=>`<div class="idea"><span class="emoji">💡</span><div class="label">${i}</div><button class="add-mini" onclick="addIdea('${i.replaceAll("'","\\'")}')">＋ Aggiungi</button></div>`).join("")}</div>`}else{body=`<div class="section-title" style="margin-bottom:10px">Storico ${currentRoom.toLowerCase()}</div><div class="timeline">${historyForRoom(currentRoom)}</div>`}return `<div class="hero-room"><div class="muted">Stanza</div><h2>${roomEmoji[currentRoom]} ${currentRoom}</h2></div>${tabs}${body}`}
function roomTab(tab){currentRoomTab=tab;render()}
function addIdea(name){state.tasks.push({id:Date.now(),name,room:currentRoom,type:"periodic",frequency:null,duration:10,lastDone:null,history:[]});save();currentRoomTab="tasks";render()}
function recentHistory(limit=4){const events=[];state.tasks.forEach(t=>(t.history||[]).forEach(d=>events.push({date:d,task:t})));events.sort((a,b)=>b.date.localeCompare(a.date));if(!events.length)return'<div class="empty">Quando completerai un’attività, comparirà qui.</div>';return events.slice(0,limit).map(e=>`<div class="task-row"><span>${roomEmoji[e.task.room]}</span><div class="task-main"><div class="task-name">${e.task.name}</div><div class="task-meta">${e.task.room}</div></div><span class="task-meta">${fmtDate(e.date)}</span></div>`).join("")}
function historyForRoom(room){const events=[];state.tasks.filter(t=>t.room===room).forEach(t=>(t.history||[]).forEach(d=>events.push({date:d,task:t})));events.sort((a,b)=>b.date.localeCompare(a.date));return events.length?events.map(e=>`<div class="event"><div class="date">${fmtDate(e.date)}</div><b>${e.task.name}</b></div>`).join(""):'<div class="empty">Nessuna attività completata in questa stanza.</div>'}
function showHistory(){state.currentView="history";render()}
function renderHistory(){const events=[];state.tasks.forEach(t=>(t.history||[]).forEach(d=>events.push({date:d,task:t})));events.sort((a,b)=>b.date.localeCompare(a.date));return `<div class="filters"><button class="active">Tutto</button>${rooms.slice(0,4).map(r=>`<button>${r}</button>`).join("")}</div><section class="section"><div class="timeline">${events.length?events.map(e=>`<div class="event"><div class="date">${fmtDate(e.date)}</div><b>${e.task.name}</b><div class="task-meta">${e.task.room}</div></div>`).join(""):'<div class="empty">Nessuno storico ancora.</div>'}</div></section>`}
function completeTask(id){const t=state.tasks.find(x=>x.id===id);if(!t)return;const d=todayISO();t.lastDone=d;t.history=t.history||[];if(!t.history.includes(d))t.history.unshift(d);state.completedToday++;save();render()}
function openTask(id){const t=state.tasks.find(x=>x.id===id);if(!t)return;document.getElementById("detail-content").innerHTML=`<div class="dialog-head"><div><div class="chip">${t.room}</div><h2 style="margin-top:10px">${t.name}</h2></div><button class="icon-btn" onclick="detailDialog.close()">✕</button></div><div class="card" style="padding:14px;margin-bottom:14px"><div class="task-meta">Tipo</div><b>${t.type==="recurring"?"Ricorrente":t.type==="periodic"?"Periodica senza scadenza":"Una tantum"}</b><div class="task-meta" style="margin-top:10px">Ultima volta</div><b>${fmtDate(t.lastDone)}</b></div><div class="section-title" style="margin-bottom:8px">Storico</div><div class="timeline">${(t.history||[]).length?(t.history||[]).map(d=>`<div class="event"><div class="date">${fmtDate(d)}</div><b>Attività completata</b></div>`).join(""):'<div class="empty">Nessuna registrazione.</div>'}</div><button class="primary full" onclick="completeTask(${t.id});detailDialog.close()">✓ Completa attività</button>`;detailDialog.showModal()}
const taskDialog=document.getElementById("task-dialog"),detailDialog=document.getElementById("detail-dialog");
document.getElementById("add-btn").addEventListener("click",()=>openAdd());
document.getElementById("history-btn").addEventListener("click",showHistory);
document.getElementById("close-task").addEventListener("click",()=>taskDialog.close());
document.querySelectorAll("#type-picker button").forEach(b=>b.addEventListener("click",()=>{selectedType=b.dataset.type;document.querySelectorAll("#type-picker button").forEach(x=>x.classList.toggle("selected",x===b));document.getElementById("frequency-wrap").style.display=selectedType==="recurring"?"block":"none"}));
function openAdd(room){document.getElementById("task-form").reset();selectedType="recurring";document.querySelectorAll("#type-picker button").forEach(x=>x.classList.toggle("selected",x.dataset.type==="recurring"));document.getElementById("frequency-wrap").style.display="block";if(room)document.getElementById("task-room").value=room;taskDialog.showModal()}
document.getElementById("task-form").addEventListener("submit",e=>{e.preventDefault();const name=document.getElementById("task-name").value.trim();if(!name){document.getElementById("task-name").focus();return}const room=document.getElementById("task-room").value;state.tasks.push({id:Date.now(),name,room,type:selectedType,frequency:selectedType==="recurring"?Number(document.getElementById("task-frequency").value):null,duration:Number(document.getElementById("task-duration").value),notes:document.getElementById("task-notes").value.trim(),lastDone:null,history:[]});save();taskDialog.close();if(state.currentView==="room")currentRoom=room;render()});
function render(){const title=document.getElementById("page-title"),c=document.getElementById("content"),view=state.currentView;document.querySelector(".eyebrow").textContent=view==="room"?currentRoom:view==="history"?"Storico casa":"Casa";if(view==="today"){title.textContent=new Date().toLocaleDateString("it-IT",{weekday:"long",day:"numeric",month:"long"});c.innerHTML=renderToday()}if(view==="cleaning"){title.textContent="Pulizie";c.innerHTML=renderCleaning()}if(view==="routines"){title.textContent="Routine";c.innerHTML=renderRoutines()}if(view==="home"){title.textContent="Casa";c.innerHTML=renderHome()}if(view==="room"){title.textContent=currentRoom;c.innerHTML=renderRoom()}if(view==="history"){title.textContent="Storico";c.innerHTML=renderHistory()}}
render();
